// Code generated by sanitizer; DO NOT EDIT.

package mask_types

func (v Customer) Sanitize() Customer {
	v.Name = v.Name.Sanitize()
	v.Phone = v.Phone.Sanitize()
	v.Email = v.Email.Sanitize()
	v.Card = v.Card.Sanitize()
	return v
}
