// Code generated by pii; DO NOT EDIT.

package pointer_slice

func (v Address) Sanitize() Address {
	v.Zip = v.Zip.Sanitize()
	return v
}

func (v User) Sanitize() User {
	v.Phones = append(v.Phones[:0:0], v.Phones...)
	for i := range v.Phones {
		v.Phones[i] = v.Phones[i].Sanitize()
	}
	if v.Address != nil {
		tmp := (*v.Address).Sanitize()
		v.Address = &tmp
	}
	return v
}
