// Code generated by pii; DO NOT EDIT.

package nested

func (v ContactInfo) Sanitize() ContactInfo {
	v.Phone = v.Phone.Sanitize()
	v.Email = v.Email.Sanitize()
	return v
}

func (v User) Sanitize() User {
	v.ContactInfo = v.ContactInfo.Sanitize()
	return v
}
