package generator

import "github.com/alifengineer/pii/internal/analyzer"

func (g *generator) emitHeader(packageName string) {
	g.p("// Code generated by sanitizer; DO NOT EDIT.")
	g.p("")
	g.p("package %s", packageName)
}

func (g *generator) emitSanitizeMethod(target analyzer.SanitizeTarget, alloc identifierAllocator) {
	g.p("")
	g.p("func (v %s) Sanitize() %s {", target.StructName, target.StructName)
	g.in()
	for _, f := range target.Fields {
		g.emitField(f, alloc)
	}
	g.p("return v")
	g.out()
	g.p("}")
}

func (g *generator) emitField(f analyzer.TargetField, alloc identifierAllocator) {
	switch f.Action {
	case analyzer.ActionSanitize:
		g.emitSanitize(f.Name)
	case analyzer.ActionSanitizePtr:
		g.emitSanitizePtr(f.Name, alloc)
	case analyzer.ActionSanitizeSlice:
		g.emitSanitizeSlice(f.Name)
	case analyzer.ActionSanitizePtrSlice:
		g.emitSanitizePtrSlice(f.Name, alloc)
	case analyzer.ActionCopy:
		// no-op
	}
}

func (g *generator) emitSanitize(fieldName string) {
	g.p("v.%s = v.%s.Sanitize()", fieldName, fieldName)
}

func (g *generator) emitSanitizePtr(fieldName string, alloc identifierAllocator) {
	tmp := alloc.allocate("tmp")
	g.p("if v.%s != nil {", fieldName)
	g.in()
	g.p("%s := (*v.%s).Sanitize()", tmp, fieldName)
	g.p("v.%s = &%s", fieldName, tmp)
	g.out()
	g.p("}")
}

func (g *generator) emitSanitizeSlice(fieldName string) {
	g.p("v.%s = append(v.%s[:0:0], v.%s...)", fieldName, fieldName, fieldName)
	g.p("for i := range v.%s {", fieldName)
	g.in()
	g.p("v.%s[i] = v.%s[i].Sanitize()", fieldName, fieldName)
	g.out()
	g.p("}")
}

func (g *generator) emitSanitizePtrSlice(fieldName string, alloc identifierAllocator) {
	tmp := alloc.allocate("tmp")
	g.p("v.%s = append(v.%s[:0:0], v.%s...)", fieldName, fieldName, fieldName)
	g.p("for i := range v.%s {", fieldName)
	g.in()
	g.p("if v.%s[i] != nil {", fieldName)
	g.in()
	g.p("%s := (*v.%s[i]).Sanitize()", tmp, fieldName)
	g.p("v.%s[i] = &%s", fieldName, tmp)
	g.out()
	g.p("}")
	g.out()
	g.p("}")
}
