package generator

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/alifengineer/pii/internal/analyzer"
)

func TestGenerate_BasicStruct(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "User",
			Fields: []analyzer.TargetField{
				{Name: "Name", Action: analyzer.ActionCopy},
				{Name: "Phone", Action: analyzer.ActionSanitize},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("basic", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	t.Log("Generated output:\n" + got)

	assertContains(t, got, "// Code generated by pii; DO NOT EDIT.")
	assertContains(t, got, "package basic")
	assertContains(t, got, "func (v User) Sanitize() User {")
	assertContains(t, got, "v.Phone = v.Phone.Sanitize()")
	assertContains(t, got, "return v")
	assertNotContains(t, got, "v.Name")
}

func TestGenerate_NestedStructs(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "ContactInfo",
			Fields: []analyzer.TargetField{
				{Name: "Phone", Action: analyzer.ActionSanitize},
				{Name: "Email", Action: analyzer.ActionSanitize},
			},
		},
		{
			StructName: "User",
			Fields: []analyzer.TargetField{
				{Name: "Name", Action: analyzer.ActionCopy},
				{Name: "ContactInfo", Action: analyzer.ActionSanitize},
				{Name: "Address", Action: analyzer.ActionCopy},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("nested", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	assertContains(t, got, "func (v ContactInfo) Sanitize() ContactInfo {")
	assertContains(t, got, "v.Phone = v.Phone.Sanitize()")
	assertContains(t, got, "v.Email = v.Email.Sanitize()")
	assertContains(t, got, "func (v User) Sanitize() User {")
	assertContains(t, got, "v.ContactInfo = v.ContactInfo.Sanitize()")
}

func TestGenerate_PointerField(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "Wrapper",
			Fields: []analyzer.TargetField{
				{Name: "Addr", Action: analyzer.ActionSanitizePtr},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("pkg", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	assertContains(t, got, "if v.Addr != nil {")
	assertContains(t, got, "tmp := (*v.Addr).Sanitize()")
	assertContains(t, got, "v.Addr = &tmp")
}

func TestGenerate_MaskSlice(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "Wrapper",
			Fields: []analyzer.TargetField{
				{Name: "Phones", Action: analyzer.ActionSanitizeSlice},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("pkg", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	assertContains(t, got, "for i := range v.Phones {")
	assertContains(t, got, "v.Phones[i] = v.Phones[i].Sanitize()")
}

func TestGenerate_SanitizePtrSlice(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "Wrapper",
			Fields: []analyzer.TargetField{
				{Name: "Items", Action: analyzer.ActionSanitizePtrSlice},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("pkg", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	assertContains(t, got, "for i := range v.Items {")
	assertContains(t, got, "if v.Items[i] != nil {")
	assertContains(t, got, "(*v.Items[i]).Sanitize()")
}

func TestIdentifierAllocator(t *testing.T) {
	alloc := newIdentifierAllocator()
	first := alloc.allocate("tmp")
	if first != "tmp" {
		t.Errorf("first = %q, want %q", first, "tmp")
	}
	second := alloc.allocate("tmp")
	if second != "tmp_0" {
		t.Errorf("second = %q, want %q", second, "tmp_0")
	}
	third := alloc.allocate("tmp")
	if third != "tmp_1" {
		t.Errorf("third = %q, want %q", third, "tmp_1")
	}
	other := alloc.allocate("i")
	if other != "i" {
		t.Errorf("other = %q, want %q", other, "i")
	}
}

func TestShouldWrite_FileNotExist(t *testing.T) {
	if !ShouldWrite([]byte("hello"), "/tmp/nonexistent_pi_test_file.go") {
		t.Error("ShouldWrite should return true for nonexistent file")
	}
}

func TestShouldWrite_Unchanged(t *testing.T) {
	path := t.TempDir() + "/test.go"
	content := []byte("package test\n")
	if err := WriteFile(content, path); err != nil {
		t.Fatal(err)
	}
	if ShouldWrite(content, path) {
		t.Error("ShouldWrite should return false for unchanged content")
	}
}

func TestShouldWrite_Changed(t *testing.T) {
	path := t.TempDir() + "/test.go"
	if err := WriteFile([]byte("old"), path); err != nil {
		t.Fatal(err)
	}
	if !ShouldWrite([]byte("new"), path) {
		t.Error("ShouldWrite should return true for changed content")
	}
}

func TestEmitHeader(t *testing.T) {
	buf := new(bytes.Buffer)
	g := newGenerator(buf)
	g.emitHeader("mypkg")

	got := buf.String()
	assertContains(t, got, "// Code generated by pii; DO NOT EDIT.")
	assertContains(t, got, "package mypkg")
}

func TestEmitIndentation(t *testing.T) {
	buf := new(bytes.Buffer)
	g := newGenerator(buf)
	g.p("func foo() {")
	g.in()
	g.p("return")
	g.out()
	g.p("}")

	want := "func foo() {\n\treturn\n}\n"
	if buf.String() != want {
		t.Errorf("got:\n%s\nwant:\n%s", buf.String(), want)
	}
}

func assertContains(t *testing.T, got, want string) {
	t.Helper()
	if !bytes.Contains([]byte(got), []byte(want)) {
		t.Errorf("output missing %q\n\nfull output:\n%s", want, got)
	}
}

func assertNotContains(t *testing.T, got, want string) {
	t.Helper()
	if bytes.Contains([]byte(got), []byte(want)) {
		t.Errorf("output should not contain %q\n\nfull output:\n%s", want, got)
	}
}

func TestMultiplePointerFields_IdentAlloc(t *testing.T) {
	targets := []analyzer.SanitizeTarget{
		{
			StructName: "Multi",
			Fields: []analyzer.TargetField{
				{Name: "A", Action: analyzer.ActionSanitizePtr},
				{Name: "B", Action: analyzer.ActionSanitizePtr},
			},
		},
	}

	buf := new(bytes.Buffer)
	output, err := Generate("pkg", targets, buf)
	if err != nil {
		t.Fatal(err)
	}

	got := string(output)
	assertContains(t, got, "tmp := (*v.A).Sanitize()")
	assertContains(t, got, "tmp_0 := (*v.B).Sanitize()")
	fmt.Println(got)
}
