// Code generated by sanitizer; DO NOT EDIT.

package type_filter

func (v ContactInfo) Sanitize() ContactInfo {
	v.Phone = v.Phone.Sanitize()
	return v
}

func (v User) Sanitize() User {
	v.Contact = v.Contact.Sanitize()
	return v
}
